import type { Metadata } from "next";
import "./globals.css";
import { myFontMedium } from "./fonts";

export const metadata: Metadata = {
  title: "Monito",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={myFontMedium.className}>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body>{children}</body>
    </html>
  );
}
